:hardbreaks:
== Decyzje architektoniczne

=== Usuwanie martwego kodu

Usuwanie wyrażeń z modelu reprezentacji pośredniej niebędących w użyciu przez inne wyrażenia.

Cel decyzji ::
    "Odchudzenie" struktury modelu reprezentacji pośredniej.

Kryteria decyzyjne ::
    * ograniczenie nadmiernych operacji w wyniku przetwarzania modelu.
    * zmniejszenie ilości kodu wynikowego translacji

Alternatywy ::
    * pozostawienie nieużytych wyrażeń

=== Zliczanie ilości użyć obiektu w celu zastosowania jego nazwy w miejscu jego wystąpienia

Użycia obiektu w wyrażeniach przypisanych do innych będą zliczane w celu zastosowania w kodzie wynikowym ich wyrażeń w postaci nazwy obiektu w przypadku więcej niż jednego wystąpienia. 
Za zliczanie wystąpień obiektów będzie odpowiadała klasa *AssignmentObject*.

Cel decyzji ::
    Ustalenie sposobu przekazywania wyrażeń obiektów używanych wielorazowo.

Kryteria decyzyjne ::
    * prostota kodu wynikowego translacji

Alternatywy ::
    * używanie wyrażenia przypisanego do obiektu w miejscu jego użycia

=== Przypisywanie obiektowi nazw obiektów go używających

Po wykryciu użycia obiektu w wyrażeniu innego, instancji *AssignmentObject* odpowiadającej za dany obiekt przypisywana będzie nazwa obiektu z niego korzystającego. W każdej instancji *AssignmentObject* liczone są nazwy obietków korzystających, ich ilość będzie odpowiadać za ilość zastosowań obiektu używanego.
W przypadku usuwania martwego kodu, przed zliczeniem nazw obiektów korzystających z danego obiektu, te znajdujące się w lesie wyrażenia z operatorem przypisania trwałego (persistent assignment) zostaną potwierdzone we wszystkich instancjach zliczających (czego nie umożliwia zliczanie poprzez wpisywanie do zmiennej typu numerycznego). Tylko potwierdzone obiekty będą zliczane. Instancje, które nie odpowiadają za trwałe przypisanie (persistent assignment), posiadające 0 użyć będą usuwane jako martwy kod.

Cel decyzji ::
    Ustalenie sposobu zliczania obiektu używanego wielorazowo.

Kryteria decyzyjne::
    * optymalne zliczanie użyć wyrażenia obiektu
    * przyszłe wykorzystanie w usuwaniu martwego kodu

Alternatywy ::
    * zliczanie użyć obiektów poprzez wpisywanie do zmiennej typu numerycznego

=== Użycie stałych

Przypisania będą odbywać się jednorazowo, to znaczy po przypisaniu wyrażenia do obiektu A, nie będzie można tego zrobić ponownie w nowym poleceniu. Ułatwi to zliczanie wystąpień wyrażeń obiektów w kodzie wynikowym, gdyż ich użycia nie będą się nagle pojawiały w kolejnych przypisywanych wyrażeniach.

====
A := 3 + 1;
[line-through]#A := 7 + 2;# *błąd*
====

Cel decyzji ::
    Ustalenie krotności przypisywania wyrażeń do obiektów mającej wpływ na kwestię sposobu zliczania użyć tych obiektów przez inne.

Kryteria decyzyjne ::
    * nie wszystkie języki docelowe obsługują nadpisywanie wartości zmiennych
    * najprostsza implementacja zliczania wystąpień:
    ** jednorazowe przejście po drzewie w celu uzyskania wyników
    ** przejrzysty model danych
    ** przystępna logika
    ** prostota stworzenia kodu źródłowego

Alternatywy ::
    * użycie zmiennych

=== Zliczanie ilości użyć wyrażenia w celu zastosowania go jako stałej

Użycia wyrażenia będą zliczane w celu ich zastosowania w kodzie wynikowym w postaci nazwy stałej w przypadku więcej niż jednego wystąpienia.

Cel decyzji ::
    Ustalenie sposobu przekazywania wyrażeń używanych wielorazowo.

Kryteria decyzyjne ::
    * prostota kodu wynikowego translacji

Alternatywy ::
    * używanie wyrażenia w miejscu jego użycia

=== Target.TSQL jako biblioteka .Net Core 3.0

Target wykonujący translację do języka T-SQL na podstawie schematu transformacji będzie biblioteką .Net Core 3.0.

Cel decyzji ::
    Ustalenie w jakiej technologii odbędzie się proces translacji.

Kryteria decyzyjne ::
    * obeznanie z narzędziem przez zespół programistyczny
    * optymalne wykorzystanie schematu transformacji
    * możliwość konfiguracji

Alternatywy ::
    * String Template

=== Transformacja operatorów działających na zestawach danych na opeartor join

Działania, które w bardzo podobny sposób można przedstawić w T-SQL przy pomocy warunku join będą transformowane do postaci operatora join przy pomocy odpowiedniego modyfikatora w warstwie middle-end.

Cel decyzji ::
    Uproszczenie mechanizmu translacji operatorów wykorzystujących warunek join.

Kryteria decyzyjne ::
    * ujednolicenie sposobu translacji

Alternatywy ::
    * tworzenie warunku join w każdym wymagającym go rendererze operatora

=== Integracja typów numerycznych

W działaniach na liczbach będzie możliwe użycie obydwu typów numerycznych razem. Wyniki operacji na nich prezetują się następująco:

====
a) Integer + Integer = Integer
b) Integer + Number = Number
c) Number + Number = Number
d) Number + Integer = Number
====

Cel decyzji ::
    Ustalenie zachowań typów numerycznych.

Kryteria decyzyjne ::
    * uwzględnienie zachowań typów numerycznych w większości możliwych językach docelowych

Alternatywy ::
    * brak możliwości operacji pomiędzy dwoma typami numeryczymi

=== Null jako dowolny typ

Wartość NULL będzie traktowana jako dowolny typ danych pasujący do wszystkiego. W połączeniu z dowolnym typem danych zwracany jest dany typ. Połączenie z drugim NULL'em zwróci NULL.

Cel decyzji ::
    Ustalenie sposobu zachowań operacji zawierających wartość NULL.

Kryteria decyzyjne ::
    * obsługa zwróconego typu danych w schemacie transformacji
    * uwzględnienie zachowań operacji zawierających wartość NULL w T-SQL

Alternatywy ::
    * cokolwiek w połączeniu z NULL'em zwraca NULL
    * brak możliwości użycia wartości NULL w większości operatorów

=== Stałe typu czasowego poprzedzone literą t

Stałe typu czasowego będą przedstawiane w postaci string'a poprzedzonego literą t.

====
a) t"2020-04-30"
b) t"2020Q2"
====

Cel decyzji ::
    Ustalenie sposobu przedstawienia stałych typu czasowego.

Kryteria decyzyjne ::
    * prostota zapisu

Alternatywy ::
    * inne kombinacje string'ów i symboli

:!hardbreaks:

