CREATE TABLE [Greater_than].[DS_2]
(
	[Id_1] VARCHAR(32) NOT NULL,
	[Id_2] VARCHAR(32) NOT NULL,
	[Id_3] VARCHAR(32) NOT NULL,
	[Id_4] VARCHAR(32) NOT NULL,
	[Me_1] DECIMAL(28,9),
	CONSTRAINT [PK_Greater_than_DS_2] PRIMARY KEY CLUSTERED ([Id_1], [Id_2], [Id_3], [Id_4])
)
