site:
  title: VTL Processing Documentation
  url: https://statisticspoland.github.io/VTL-Processing
  start_page: vtl_arch::index.adoc 
content:
  sources:
  - url: ..
    start_path: docs-source/Architecture
    branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  #supplemental_files: ./supplemental_ui
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
