//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Vtl.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace StatisticsPoland.VtlProcessing.Core.FrontEnd.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVtlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class VtlBaseListener : IVtlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] VtlParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] VtlParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] VtlParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] VtlParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.dataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataset([NotNull] VtlParser.DatasetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.dataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataset([NotNull] VtlParser.DatasetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.openedDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpenedDataset([NotNull] VtlParser.OpenedDatasetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.openedDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpenedDataset([NotNull] VtlParser.OpenedDatasetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.closedDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClosedDataset([NotNull] VtlParser.ClosedDatasetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.closedDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClosedDataset([NotNull] VtlParser.ClosedDatasetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.membershipDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMembershipDataset([NotNull] VtlParser.MembershipDatasetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.membershipDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMembershipDataset([NotNull] VtlParser.MembershipDatasetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.datasetComplex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatasetComplex([NotNull] VtlParser.DatasetComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.datasetComplex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatasetComplex([NotNull] VtlParser.DatasetComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ifThenElseDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfThenElseDataset([NotNull] VtlParser.IfThenElseDatasetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ifThenElseDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfThenElseDataset([NotNull] VtlParser.IfThenElseDatasetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.unopenedDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnopenedDataset([NotNull] VtlParser.UnopenedDatasetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.unopenedDataset"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnopenedDataset([NotNull] VtlParser.UnopenedDatasetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponent([NotNull] VtlParser.ComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.component"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponent([NotNull] VtlParser.ComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.scalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalar([NotNull] VtlParser.ScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.scalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalar([NotNull] VtlParser.ScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ifThenElseScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfThenElseScalar([NotNull] VtlParser.IfThenElseScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ifThenElseScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfThenElseScalar([NotNull] VtlParser.IfThenElseScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.optionalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalExpr([NotNull] VtlParser.OptionalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.optionalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalExpr([NotNull] VtlParser.OptionalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.setExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetExpr([NotNull] VtlParser.SetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.setExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetExpr([NotNull] VtlParser.SetExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.datasetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatasetClause([NotNull] VtlParser.DatasetClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.datasetClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatasetClause([NotNull] VtlParser.DatasetClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrClause([NotNull] VtlParser.AggrClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrClause([NotNull] VtlParser.AggrClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrExpr([NotNull] VtlParser.AggrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrExpr([NotNull] VtlParser.AggrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.filterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilterClause([NotNull] VtlParser.FilterClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.filterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilterClause([NotNull] VtlParser.FilterClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.renameClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRenameClause([NotNull] VtlParser.RenameClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.renameClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRenameClause([NotNull] VtlParser.RenameClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.renameExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRenameExpr([NotNull] VtlParser.RenameExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.renameExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRenameExpr([NotNull] VtlParser.RenameExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.calcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCalcClause([NotNull] VtlParser.CalcClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.calcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCalcClause([NotNull] VtlParser.CalcClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.calcExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCalcExpr([NotNull] VtlParser.CalcExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.calcExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCalcExpr([NotNull] VtlParser.CalcExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.keepClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeepClause([NotNull] VtlParser.KeepClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.keepClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeepClause([NotNull] VtlParser.KeepClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.dropClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropClause([NotNull] VtlParser.DropClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.dropClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropClause([NotNull] VtlParser.DropClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.pivotClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPivotClause([NotNull] VtlParser.PivotClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.pivotClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPivotClause([NotNull] VtlParser.PivotClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.unpivotClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnpivotClause([NotNull] VtlParser.UnpivotClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.unpivotClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnpivotClause([NotNull] VtlParser.UnpivotClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.subspaceClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubspaceClause([NotNull] VtlParser.SubspaceClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.subspaceClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubspaceClause([NotNull] VtlParser.SubspaceClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.subspaceExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubspaceExpr([NotNull] VtlParser.SubspaceExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.subspaceExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubspaceExpr([NotNull] VtlParser.SubspaceExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinExpr([NotNull] VtlParser.JoinExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinExpr([NotNull] VtlParser.JoinExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinClause([NotNull] VtlParser.JoinClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinClause([NotNull] VtlParser.JoinClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinBody([NotNull] VtlParser.JoinBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinBody([NotNull] VtlParser.JoinBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinAliasesClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinAliasesClause([NotNull] VtlParser.JoinAliasesClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinAliasesClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinAliasesClause([NotNull] VtlParser.JoinAliasesClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinAliasExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinAliasExpr([NotNull] VtlParser.JoinAliasExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinAliasExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinAliasExpr([NotNull] VtlParser.JoinAliasExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinUsingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinUsingClause([NotNull] VtlParser.JoinUsingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinUsingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinUsingClause([NotNull] VtlParser.JoinUsingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinCalcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinCalcClause([NotNull] VtlParser.JoinCalcClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinCalcClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinCalcClause([NotNull] VtlParser.JoinCalcClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinAggrClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinAggrClause([NotNull] VtlParser.JoinAggrClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinAggrClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinAggrClause([NotNull] VtlParser.JoinAggrClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinKeepClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinKeepClause([NotNull] VtlParser.JoinKeepClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinKeepClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinKeepClause([NotNull] VtlParser.JoinKeepClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinDropClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinDropClause([NotNull] VtlParser.JoinDropClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinDropClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinDropClause([NotNull] VtlParser.JoinDropClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinFilterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinFilterClause([NotNull] VtlParser.JoinFilterClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinFilterClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinFilterClause([NotNull] VtlParser.JoinFilterClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinRenameClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinRenameClause([NotNull] VtlParser.JoinRenameClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinRenameClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinRenameClause([NotNull] VtlParser.JoinRenameClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinApplyClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinApplyClause([NotNull] VtlParser.JoinApplyClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinApplyClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinApplyClause([NotNull] VtlParser.JoinApplyClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrInvocation([NotNull] VtlParser.AggrInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrInvocation([NotNull] VtlParser.AggrInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrFunction([NotNull] VtlParser.AggrFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrFunction([NotNull] VtlParser.AggrFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrFunctionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggrFunctionName([NotNull] VtlParser.AggrFunctionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrFunctionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggrFunctionName([NotNull] VtlParser.AggrFunctionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.groupingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupingClause([NotNull] VtlParser.GroupingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.groupingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupingClause([NotNull] VtlParser.GroupingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.havingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHavingClause([NotNull] VtlParser.HavingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.havingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHavingClause([NotNull] VtlParser.HavingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.havingExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHavingExpr([NotNull] VtlParser.HavingExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.havingExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHavingExpr([NotNull] VtlParser.HavingExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnalyticInvocation([NotNull] VtlParser.AnalyticInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnalyticInvocation([NotNull] VtlParser.AnalyticInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnalyticFunction([NotNull] VtlParser.AnalyticFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnalyticFunction([NotNull] VtlParser.AnalyticFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnalyticClause([NotNull] VtlParser.AnalyticClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnalyticClause([NotNull] VtlParser.AnalyticClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.partitionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartitionClause([NotNull] VtlParser.PartitionClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.partitionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartitionClause([NotNull] VtlParser.PartitionClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderClause([NotNull] VtlParser.OrderClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderClause([NotNull] VtlParser.OrderClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.orderExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderExpr([NotNull] VtlParser.OrderExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.orderExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderExpr([NotNull] VtlParser.OrderExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.windowingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindowingClause([NotNull] VtlParser.WindowingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.windowingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindowingClause([NotNull] VtlParser.WindowingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.firstWindowLimit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirstWindowLimit([NotNull] VtlParser.FirstWindowLimitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.firstWindowLimit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirstWindowLimit([NotNull] VtlParser.FirstWindowLimitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.secondWindowLimit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSecondWindowLimit([NotNull] VtlParser.SecondWindowLimitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.secondWindowLimit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSecondWindowLimit([NotNull] VtlParser.SecondWindowLimitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticFunctionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnalyticFunctionName([NotNull] VtlParser.AnalyticFunctionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticFunctionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnalyticFunctionName([NotNull] VtlParser.AnalyticFunctionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] VtlParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] VtlParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.varID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarID([NotNull] VtlParser.VarIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.varID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarID([NotNull] VtlParser.VarIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.datasetID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDatasetID([NotNull] VtlParser.DatasetIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.datasetID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDatasetID([NotNull] VtlParser.DatasetIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.componentID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponentID([NotNull] VtlParser.ComponentIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.componentID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponentID([NotNull] VtlParser.ComponentIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoinKeyword([NotNull] VtlParser.JoinKeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoinKeyword([NotNull] VtlParser.JoinKeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.groupKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupKeyword([NotNull] VtlParser.GroupKeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.groupKeyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupKeyword([NotNull] VtlParser.GroupKeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] VtlParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] VtlParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.componentRole"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponentRole([NotNull] VtlParser.ComponentRoleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.componentRole"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponentRole([NotNull] VtlParser.ComponentRoleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.valueDomainName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueDomainName([NotNull] VtlParser.ValueDomainNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.valueDomainName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueDomainName([NotNull] VtlParser.ValueDomainNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.retainType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetainType([NotNull] VtlParser.RetainTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.retainType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetainType([NotNull] VtlParser.RetainTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.limitsMethod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimitsMethod([NotNull] VtlParser.LimitsMethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.limitsMethod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimitsMethod([NotNull] VtlParser.LimitsMethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.checkDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCheckDatapoint([NotNull] VtlParser.CheckDatapointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.checkDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCheckDatapoint([NotNull] VtlParser.CheckDatapointContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.defExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefExpr([NotNull] VtlParser.DefExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.defExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefExpr([NotNull] VtlParser.DefExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.defDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefDatapoint([NotNull] VtlParser.DefDatapointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.defDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefDatapoint([NotNull] VtlParser.DefDatapointContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.rulesetSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRulesetSignature([NotNull] VtlParser.RulesetSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.rulesetSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRulesetSignature([NotNull] VtlParser.RulesetSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ruleClauseDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleClauseDatapoint([NotNull] VtlParser.RuleClauseDatapointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ruleClauseDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleClauseDatapoint([NotNull] VtlParser.RuleClauseDatapointContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ruleItemDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleItemDatapoint([NotNull] VtlParser.RuleItemDatapointContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ruleItemDatapoint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleItemDatapoint([NotNull] VtlParser.RuleItemDatapointContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.varSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarSignature([NotNull] VtlParser.VarSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.varSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarSignature([NotNull] VtlParser.VarSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.errorCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterErrorCode([NotNull] VtlParser.ErrorCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.errorCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitErrorCode([NotNull] VtlParser.ErrorCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.errorLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterErrorLevel([NotNull] VtlParser.ErrorLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.errorLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitErrorLevel([NotNull] VtlParser.ErrorLevelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.rulesetID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRulesetID([NotNull] VtlParser.RulesetIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.rulesetID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRulesetID([NotNull] VtlParser.RulesetIDContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ruleID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleID([NotNull] VtlParser.RuleIDContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ruleID"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleID([NotNull] VtlParser.RuleIDContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace StatisticsPoland.VtlProcessing.Core.FrontEnd.Antlr
