//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Vtl.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace StatisticsPoland.VtlProcessing.Core.FrontEnd.Antlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VtlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IVtlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] VtlParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] VtlParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] VtlParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] VtlParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.dataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataset([NotNull] VtlParser.DatasetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.dataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataset([NotNull] VtlParser.DatasetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.openedDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenedDataset([NotNull] VtlParser.OpenedDatasetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.openedDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenedDataset([NotNull] VtlParser.OpenedDatasetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.closedDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClosedDataset([NotNull] VtlParser.ClosedDatasetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.closedDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClosedDataset([NotNull] VtlParser.ClosedDatasetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.membershipDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMembershipDataset([NotNull] VtlParser.MembershipDatasetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.membershipDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMembershipDataset([NotNull] VtlParser.MembershipDatasetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.datasetComplex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetComplex([NotNull] VtlParser.DatasetComplexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.datasetComplex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetComplex([NotNull] VtlParser.DatasetComplexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ifThenElseDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfThenElseDataset([NotNull] VtlParser.IfThenElseDatasetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ifThenElseDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfThenElseDataset([NotNull] VtlParser.IfThenElseDatasetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.unopenedDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnopenedDataset([NotNull] VtlParser.UnopenedDatasetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.unopenedDataset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnopenedDataset([NotNull] VtlParser.UnopenedDatasetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponent([NotNull] VtlParser.ComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.component"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponent([NotNull] VtlParser.ComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.scalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalar([NotNull] VtlParser.ScalarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.scalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalar([NotNull] VtlParser.ScalarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ifThenElseScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfThenElseScalar([NotNull] VtlParser.IfThenElseScalarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ifThenElseScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfThenElseScalar([NotNull] VtlParser.IfThenElseScalarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.optionalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalExpr([NotNull] VtlParser.OptionalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.optionalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalExpr([NotNull] VtlParser.OptionalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpr([NotNull] VtlParser.SetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.setExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpr([NotNull] VtlParser.SetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetClause([NotNull] VtlParser.DatasetClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.datasetClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetClause([NotNull] VtlParser.DatasetClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrClause([NotNull] VtlParser.AggrClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrClause([NotNull] VtlParser.AggrClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrExpr([NotNull] VtlParser.AggrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrExpr([NotNull] VtlParser.AggrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilterClause([NotNull] VtlParser.FilterClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.filterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilterClause([NotNull] VtlParser.FilterClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.renameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRenameClause([NotNull] VtlParser.RenameClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.renameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRenameClause([NotNull] VtlParser.RenameClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.renameExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRenameExpr([NotNull] VtlParser.RenameExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.renameExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRenameExpr([NotNull] VtlParser.RenameExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.calcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalcClause([NotNull] VtlParser.CalcClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.calcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalcClause([NotNull] VtlParser.CalcClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.calcExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalcExpr([NotNull] VtlParser.CalcExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.calcExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalcExpr([NotNull] VtlParser.CalcExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.keepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeepClause([NotNull] VtlParser.KeepClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.keepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeepClause([NotNull] VtlParser.KeepClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.dropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDropClause([NotNull] VtlParser.DropClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.dropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDropClause([NotNull] VtlParser.DropClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.pivotClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPivotClause([NotNull] VtlParser.PivotClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.pivotClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPivotClause([NotNull] VtlParser.PivotClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.unpivotClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnpivotClause([NotNull] VtlParser.UnpivotClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.unpivotClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnpivotClause([NotNull] VtlParser.UnpivotClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.subspaceClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubspaceClause([NotNull] VtlParser.SubspaceClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.subspaceClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubspaceClause([NotNull] VtlParser.SubspaceClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.subspaceExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubspaceExpr([NotNull] VtlParser.SubspaceExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.subspaceExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubspaceExpr([NotNull] VtlParser.SubspaceExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinExpr([NotNull] VtlParser.JoinExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinExpr([NotNull] VtlParser.JoinExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinClause([NotNull] VtlParser.JoinClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinClause([NotNull] VtlParser.JoinClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinBody([NotNull] VtlParser.JoinBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinBody([NotNull] VtlParser.JoinBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinAliasesClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinAliasesClause([NotNull] VtlParser.JoinAliasesClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinAliasesClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinAliasesClause([NotNull] VtlParser.JoinAliasesClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinAliasExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinAliasExpr([NotNull] VtlParser.JoinAliasExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinAliasExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinAliasExpr([NotNull] VtlParser.JoinAliasExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinUsingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinUsingClause([NotNull] VtlParser.JoinUsingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinUsingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinUsingClause([NotNull] VtlParser.JoinUsingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinCalcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinCalcClause([NotNull] VtlParser.JoinCalcClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinCalcClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinCalcClause([NotNull] VtlParser.JoinCalcClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinAggrClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinAggrClause([NotNull] VtlParser.JoinAggrClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinAggrClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinAggrClause([NotNull] VtlParser.JoinAggrClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinKeepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinKeepClause([NotNull] VtlParser.JoinKeepClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinKeepClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinKeepClause([NotNull] VtlParser.JoinKeepClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinDropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinDropClause([NotNull] VtlParser.JoinDropClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinDropClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinDropClause([NotNull] VtlParser.JoinDropClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinFilterClause([NotNull] VtlParser.JoinFilterClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinFilterClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinFilterClause([NotNull] VtlParser.JoinFilterClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinRenameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinRenameClause([NotNull] VtlParser.JoinRenameClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinRenameClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinRenameClause([NotNull] VtlParser.JoinRenameClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinApplyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinApplyClause([NotNull] VtlParser.JoinApplyClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinApplyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinApplyClause([NotNull] VtlParser.JoinApplyClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrInvocation([NotNull] VtlParser.AggrInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrInvocation([NotNull] VtlParser.AggrInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrFunction([NotNull] VtlParser.AggrFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrFunction([NotNull] VtlParser.AggrFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.aggrFunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggrFunctionName([NotNull] VtlParser.AggrFunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.aggrFunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggrFunctionName([NotNull] VtlParser.AggrFunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.groupingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupingClause([NotNull] VtlParser.GroupingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.groupingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupingClause([NotNull] VtlParser.GroupingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHavingClause([NotNull] VtlParser.HavingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.havingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHavingClause([NotNull] VtlParser.HavingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.havingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHavingExpr([NotNull] VtlParser.HavingExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.havingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHavingExpr([NotNull] VtlParser.HavingExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnalyticInvocation([NotNull] VtlParser.AnalyticInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnalyticInvocation([NotNull] VtlParser.AnalyticInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnalyticFunction([NotNull] VtlParser.AnalyticFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnalyticFunction([NotNull] VtlParser.AnalyticFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnalyticClause([NotNull] VtlParser.AnalyticClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnalyticClause([NotNull] VtlParser.AnalyticClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartitionClause([NotNull] VtlParser.PartitionClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartitionClause([NotNull] VtlParser.PartitionClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderClause([NotNull] VtlParser.OrderClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderClause([NotNull] VtlParser.OrderClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.orderExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderExpr([NotNull] VtlParser.OrderExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.orderExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderExpr([NotNull] VtlParser.OrderExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.windowingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindowingClause([NotNull] VtlParser.WindowingClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.windowingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindowingClause([NotNull] VtlParser.WindowingClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.firstWindowLimit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFirstWindowLimit([NotNull] VtlParser.FirstWindowLimitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.firstWindowLimit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFirstWindowLimit([NotNull] VtlParser.FirstWindowLimitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.secondWindowLimit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecondWindowLimit([NotNull] VtlParser.SecondWindowLimitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.secondWindowLimit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecondWindowLimit([NotNull] VtlParser.SecondWindowLimitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.analyticFunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnalyticFunctionName([NotNull] VtlParser.AnalyticFunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.analyticFunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnalyticFunctionName([NotNull] VtlParser.AnalyticFunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] VtlParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] VtlParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.varID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarID([NotNull] VtlParser.VarIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.varID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarID([NotNull] VtlParser.VarIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.datasetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDatasetID([NotNull] VtlParser.DatasetIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.datasetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDatasetID([NotNull] VtlParser.DatasetIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.componentID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponentID([NotNull] VtlParser.ComponentIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.componentID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponentID([NotNull] VtlParser.ComponentIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.joinKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoinKeyword([NotNull] VtlParser.JoinKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.joinKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoinKeyword([NotNull] VtlParser.JoinKeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.groupKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupKeyword([NotNull] VtlParser.GroupKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.groupKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupKeyword([NotNull] VtlParser.GroupKeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] VtlParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] VtlParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.componentRole"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponentRole([NotNull] VtlParser.ComponentRoleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.componentRole"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponentRole([NotNull] VtlParser.ComponentRoleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.valueDomainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueDomainName([NotNull] VtlParser.ValueDomainNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.valueDomainName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueDomainName([NotNull] VtlParser.ValueDomainNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.retainType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetainType([NotNull] VtlParser.RetainTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.retainType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetainType([NotNull] VtlParser.RetainTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.limitsMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLimitsMethod([NotNull] VtlParser.LimitsMethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.limitsMethod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLimitsMethod([NotNull] VtlParser.LimitsMethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.checkDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCheckDatapoint([NotNull] VtlParser.CheckDatapointContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.checkDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCheckDatapoint([NotNull] VtlParser.CheckDatapointContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.defExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefExpr([NotNull] VtlParser.DefExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.defExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefExpr([NotNull] VtlParser.DefExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.defDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefDatapoint([NotNull] VtlParser.DefDatapointContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.defDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefDatapoint([NotNull] VtlParser.DefDatapointContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.rulesetSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRulesetSignature([NotNull] VtlParser.RulesetSignatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.rulesetSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRulesetSignature([NotNull] VtlParser.RulesetSignatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ruleClauseDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleClauseDatapoint([NotNull] VtlParser.RuleClauseDatapointContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ruleClauseDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleClauseDatapoint([NotNull] VtlParser.RuleClauseDatapointContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ruleItemDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleItemDatapoint([NotNull] VtlParser.RuleItemDatapointContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ruleItemDatapoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleItemDatapoint([NotNull] VtlParser.RuleItemDatapointContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.varSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarSignature([NotNull] VtlParser.VarSignatureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.varSignature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarSignature([NotNull] VtlParser.VarSignatureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.errorCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErrorCode([NotNull] VtlParser.ErrorCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.errorCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErrorCode([NotNull] VtlParser.ErrorCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.errorLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErrorLevel([NotNull] VtlParser.ErrorLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.errorLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErrorLevel([NotNull] VtlParser.ErrorLevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.rulesetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRulesetID([NotNull] VtlParser.RulesetIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.rulesetID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRulesetID([NotNull] VtlParser.RulesetIDContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VtlParser.ruleID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleID([NotNull] VtlParser.RuleIDContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VtlParser.ruleID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleID([NotNull] VtlParser.RuleIDContext context);
}
} // namespace StatisticsPoland.VtlProcessing.Core.FrontEnd.Antlr
