name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x 
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install sonar-scanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Begin scan
      run: >
          dotnet sonarscanner begin 
          /k:"StatisticsPoland.VtlProcessing.Core" 
          /n:"StatisticsPoland.VtlProcessing.Core" 
          /d:sonar.host.url="https://sonarcloud.io"  
          /d:sonar.login="${{ env.SONAR_TOKEN }}" 
          /o:"vtl-processing"
          /d:sonar.verbose="true"
          /d:sonar.cs.opencover.reportsPaths='"./coverage.opencover.xml"'
          /d:sonar.coverage.exclusions='"Core.App/**/*", Core.Tests/**/*'
    - name: Build
      run: dotnet build
    - name: Run tests
      run: |
          dotnet publish ./TestDatabase/TestDatabase.csproj --no-build
          dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory results ; 
          cp results/*/coverage.opencover.xml .
    - name: End scan
      run: dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"
    env:
      SONAR_TOKEN: 8784854f6b0cc1faec30dd20d476ace9af8a740e
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
