name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301 
    - name: Setup encoding
      run: sudo apt-get update 
           sudo apt-get install -y locales
           sudo locale-gen "en_US.UTF-8"
           sudo update-locale LC_ALL="en_US.UTF-8"
           sudo export LANG="en_US.UTF-8"
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build --configuration Release
        testCommand: dotnet test --no-restore --verbosity normal
        projectKey: StatisticsPoland.VtlProcessing.Core
        projectName: StatisticsPoland.VtlProcessing.Core
        sonarOrganisation: vtl-processing
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='"./coverage.xml"'
            /d:sonar.coverage.exclusions='"**/*.adoc", Docs/**/*'
    env:
      SONAR_TOKEN: 8784854f6b0cc1faec30dd20d476ace9af8a740e
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
