name: BuildAndDeployDemo

on:
  push:
    branches: [ service_project ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: 1c021755-ff5e-46cb-9a7a-63341da2d5fc
        heroku_app_name: "vtl-processing-demo"
        heroku_email: "m.bobinski@stat.gov.pl"
        usedocker: true
        appdir: "Service"
