name: BuildAndDeployDemo

on:
  push:
    branches: [ master ]
    paths:
    - 'Service/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 601a0871-24d5-40a8-a44d-e99407e373ce
        heroku_app_name: "vtl-processing-demo"
        heroku_email: "m.bobinski@stat.gov.pl"
        usedocker: true
