name: BuildAndDeployDemo

on:
  push:
    branches: [ service_project ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: docker build --file=Service/Dockerfile -t demo:${{ github.sha }} .
    
