name: Generate Docs

on:
  push:
    branches: [ master ]
    paths:
    - 'docs-source/**'
    - '.github/workflows/**'
jobs:
  build_site:
    name: Build site with Antora
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Antora
        uses: kameshsampath/antora-site-action@v0.3.0
        with:
            antora_playbook: ./docs-source/site.yml
            antora_generator: 'antora-site-generator-lunr'
            antora_docsearch_enabled: 'true'
      - name: Upload generated site
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: "${{ github.workspace }}/docs-source/build/site"
  deploy_site:
    runs-on: ubuntu-latest
    needs: build_site
    name: Deploy GitHub Pages
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
          persist-credentials: true
     - name: Download generated site
       uses: actions/download-artifact@v1
       with:
         name: site
         path: ${{ github.workspace }}/site
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./site
